"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import Papa from "papaparse";
import {
  AlertTriangle, ArrowUpRight, Boxes, CheckCircle2, FileSpreadsheet,
  Layers3, PackageOpen, RefreshCw, Save, Search, ShieldCheck,
  Smartphone, Store, UploadCloud, Warehouse,
} from "lucide-react";
import { getFirebaseAuth } from "@/lib/firebase.client";
import { sellerProductStatusLabel, type SellerProduct } from "@/lib/sellerTypes";
import styles from "./MarketplaceCatalogCenter.module.css";

type Mode = "products" | "stock" | "import" | "mobile" | "categories";
type Seller = { id:string; uid?:string; storeName?:string; businessName?:string; companyName?:string; email?:string; status?:string };
type ImportRow = { title:string; description:string; category:string; brand:string; sku:string; price:number; stock:number; images:string[] };

const copy = {
  products:{ icon:Boxes, eyebrow:"MARKETPLACE KATALOĞU", title:"Yeni Ürün Merkezi", text:"Tüm işletme ürünlerini tek, temiz ve satıcı bazlı katalogda yönet." },
  stock:{ icon:Warehouse, eyebrow:"CANLI ENVANTER", title:"Stok Kontrol Merkezi", text:"Onaylı mağazaların stoklarını izle, kritik seviyeleri gör ve güvenle güncelle." },
  import:{ icon:UploadCloud, eyebrow:"TOPLU OPERASYON", title:"Toplu Ürün Yükleme", text:"CSV dosyasını onaylı bir mağazaya bağla; ürünleri inceleme kuyruğuna güvenle aktar." },
  mobile:{ icon:Smartphone, eyebrow:"MOBİL ÜRÜN AKIŞI", title:"Mobil Taslak Merkezi", text:"Mobil kanaldan gelen yeni sistem taslaklarını görüntüle ve kalite akışına hazırla." },
  categories:{ icon:Layers3, eyebrow:"YENİ TAKSONOMİ", title:"Kategori Merkezi", text:"Kategorileri yalnızca yeni marketplace ürünlerinden üret; eski katalogla karıştırma." },
} as const;

function money(value:number){ return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(Number(value)||0); }
function date(value?:string|null){ if(!value)return "—"; try{return new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value));}catch{return "—";} }
function normalized(record:Record<string,unknown>, names:string[]){ for(const name of names){const value=record[name];if(value!==undefined&&String(value).trim())return String(value).trim();}return ""; }
function parseNumber(value:string){ const clean=value.replace(/\s/g,"").replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(",", "."); return Number(clean); }

export default function MarketplaceCatalogCenter({mode}:{mode:Mode}){
  const meta=copy[mode]; const Icon=meta.icon;
  const [items,setItems]=useState<SellerProduct[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const [draftStock,setDraftStock]=useState<Record<string,string>>({}); const [busy,setBusy]=useState("");
  const [sellers,setSellers]=useState<Seller[]>([]); const [sellerId,setSellerId]=useState(""); const [importRows,setImportRows]=useState<ImportRow[]>([]); const [fileName,setFileName]=useState(""); const [result,setResult]=useState("");

  const api=useCallback(async(path:string, init?:RequestInit)=>{const user=getFirebaseAuth().currentUser;if(!user)throw new Error("Süper Admin oturumu gerekli.");const token=await user.getIdToken();const response=await fetch(path,{...init,headers:{Authorization:`Bearer ${token}`,...(init?.body?{"Content-Type":"application/json"}:{}),...(init?.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data?.error||"İşlem tamamlanamadı.");return data;},[]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await api("/api/admin/seller-products");setItems(data.items||[]);if(mode==="import"){const sellerData=await api("/api/admin/sellers");setSellers((sellerData.items||[]).filter((x:Seller)=>x.status==="approved"));}}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[api,mode]);
  useEffect(()=>{void load();},[load]);

  const stats=useMemo(()=>({total:items.length,live:items.filter(x=>x.status==="approved").length,pending:items.filter(x=>x.status==="pending_review").length,low:items.filter(x=>x.stock<=5).length,out:items.filter(x=>x.stock<=0).length,mobile:items.filter(x=>String(x.source||"").startsWith("mobile")).length}),[items]);
  const visible=useMemo(()=>items.filter(item=>{if(mode==="mobile"&&!String(item.source||"").startsWith("mobile"))return false;if(status!=="all"&&item.status!==status)return false;const hay=`${item.title} ${item.storeName} ${item.sku} ${item.category}`.toLocaleLowerCase("tr");return !query||hay.includes(query.toLocaleLowerCase("tr"));}),[items,mode,query,status]);
  const categories=useMemo(()=>{const map=new Map<string,{count:number,live:number,stock:number,stores:Set<string>}>();items.forEach(item=>{const name=item.category?.trim()||"Kategorisiz";const current=map.get(name)||{count:0,live:0,stock:0,stores:new Set<string>()};current.count++;current.stock+=item.stock||0;if(item.status==="approved")current.live++;if(item.storeName)current.stores.add(item.storeName);map.set(name,current);});return [...map.entries()].sort((a,b)=>b[1].count-a[1].count);},[items]);

  async function saveStock(item:SellerProduct){const next=Math.floor(Number(draftStock[item.id]??item.stock));if(!Number.isFinite(next)||next<0){setError("Stok sıfır veya daha büyük olmalı.");return;}setBusy(item.id);setError("");try{await api("/api/admin/seller-products",{method:"PATCH",body:JSON.stringify({id:item.id,action:"inventory",stock:next})});setItems(list=>list.map(row=>row.id===item.id?{...row,stock:next}:row));setDraftStock(v=>{const n={...v};delete n[item.id];return n;});setResult(`${item.title} stoğu güncellendi.`);}catch(e){setError((e as Error).message);}finally{setBusy("");}}
  function readFile(file?:File){if(!file)return;setFileName(file.name);setError("");setResult("");Papa.parse<Record<string,unknown>>(file,{header:true,skipEmptyLines:true,complete:({data})=>{const rows=data.map(record=>{const imageText=normalized(record,["gorseller","görseller","images","image_urls","image"]);return {title:normalized(record,["urun_adi","ürün_adı","title","name"]),description:normalized(record,["aciklama","açıklama","description"]),category:normalized(record,["kategori","category"]),brand:normalized(record,["marka","brand"]),sku:normalized(record,["sku","stok_kodu"]),price:parseNumber(normalized(record,["fiyat","price"])),stock:parseNumber(normalized(record,["stok","stock"]))||0,images:imageText.split(/[|;]/).map(x=>x.trim()).filter(Boolean)};}).filter(x=>x.title||x.sku);setImportRows(rows);},error:()=>setError("CSV dosyası okunamadı.")});}
  async function submitImport(){const seller=sellers.find(x=>(x.uid||x.id)===sellerId);if(!seller){setError("Önce onaylı bir mağaza seç.");return;}if(!importRows.length){setError("Geçerli bir CSV dosyası seç.");return;}setBusy("import");setError("");setResult("");try{const data=await api("/api/admin/seller-products",{method:"POST",body:JSON.stringify({ownerUid:sellerId,storeName:seller.storeName||seller.businessName||seller.companyName,items:importRows})});setResult(`${data.imported} ürün inceleme kuyruğuna aktarıldı${data.rejected?`, ${data.rejected} satır reddedildi`:""}.`);setImportRows([]);setFileName("");await load();}catch(e){setError((e as Error).message);}finally{setBusy("");}}

  return <div className={styles.page}>
    <section className={styles.hero}><div><span>{meta.eyebrow} • PAZAR.</span><h1>{meta.title}</h1><p>{meta.text}</p><div className={styles.heroLinks}><Link href="/admin/sellers"><Store/> Satıcılar</Link><Link href="/admin/seller-products"><ShieldCheck/> Onay kuyruğu</Link></div></div><div className={styles.heroIcon}><Icon/><small>LEGACY FREE</small><b>Yeni veri modeli</b></div></section>
    {error?<div className={styles.error}><AlertTriangle/>{error}</div>:null}{result?<div className={styles.success}><CheckCircle2/>{result}</div>:null}
    <section className={styles.metrics}><article><span>TOPLAM</span><strong>{stats.total}</strong><small>Yeni marketplace ürünü</small></article><article><span>YAYINDA</span><strong>{stats.live}</strong><small>Onaylı ürün</small></article><article><span>İNCELEMEDE</span><strong>{stats.pending}</strong><small>Kalite kuyruğu</small></article><article><span>{mode==="mobile"?"MOBİL":"KRİTİK STOK"}</span><strong>{mode==="mobile"?stats.mobile:stats.low}</strong><small>{mode==="mobile"?"Yeni kanal taslağı":"5 adet ve altı"}</small></article></section>

    {mode==="import"?<section className={styles.importPanel}><div className={styles.sectionTitle}><FileSpreadsheet/><div><span>CSV AKTARIM SİHİRBAZI</span><h2>Dosyanı doğrula ve mağazaya bağla</h2><p>Zorunlu sütunlar: ürün adı, açıklama, kategori, SKU, fiyat. Açıklama en az 20 karakter olmalı.</p></div></div><div className={styles.importGrid}><label><span>ONAYLI MAĞAZA</span><select value={sellerId} onChange={e=>setSellerId(e.target.value)}><option value="">Mağaza seç</option>{sellers.map(x=><option key={x.uid||x.id} value={x.uid||x.id}>{x.storeName||x.businessName||x.companyName||x.email||x.id}</option>)}</select></label><label className={styles.drop}><UploadCloud/><b>{fileName||"CSV dosyası seç"}</b><small>En fazla 200 ürün / aktarım</small><input type="file" accept=".csv,text/csv" onChange={e=>readFile(e.target.files?.[0])}/></label></div><div className={styles.previewHead}><span>{importRows.length} satır hazır</span><button disabled={busy==="import"||!importRows.length||!sellerId} onClick={()=>void submitImport()}>{busy==="import"?<RefreshCw className={styles.spin}/>:<UploadCloud/>} İnceleme kuyruğuna aktar</button></div>{importRows.length?<div className={styles.miniTable}>{importRows.slice(0,8).map((row,i)=><div key={`${row.sku}-${i}`}><b>{row.title||"Eksik ürün adı"}</b><span>{row.sku||"SKU eksik"}</span><span>{row.category||"Kategori eksik"}</span><strong>{Number.isFinite(row.price)?money(row.price):"Fiyat hatalı"}</strong></div>)}</div>:<Empty text="CSV seçildiğinde ürün önizlemesi burada görünecek."/>}</section>:null}

    {mode==="categories"?<section className={styles.content}><div className={styles.toolbar}><div><span>KATEGORİ HARİTASI</span><h2>Yeni ürünlerden oluşan yapı</h2></div><button onClick={()=>void load()}><RefreshCw/></button></div>{loading?<Loading/>:categories.length?<div className={styles.categoryGrid}>{categories.map(([name,data])=><article key={name}><Layers3/><div><span>KATEGORİ</span><h3>{name}</h3><p>{data.stores.size} mağaza • {data.stock} toplam stok</p></div><strong>{data.count}<small>ÜRÜN</small></strong><i>{data.live} yayında</i></article>)}</div>:<Empty text="Yeni satıcı ürünleri eklendiğinde kategori yapısı otomatik oluşacak."/>}</section>:null}

    {mode!=="import"&&mode!=="categories"?<section className={styles.content}><div className={styles.toolbar}><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ürün, mağaza, kategori veya SKU ara"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tüm durumlar</option>{Object.entries(sellerProductStatusLabel).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button onClick={()=>void load()}><RefreshCw/></button></div>{loading?<Loading/>:visible.length?<div className={styles.productList}>{visible.map(item=><article key={item.id}><div className={styles.image}>{item.images?.[0]?<img src={item.images[0]} alt=""/>:<PackageOpen/>}</div><div className={styles.identity}><span className={styles[item.status]}>{sellerProductStatusLabel[item.status]}</span><h3>{item.title}</h3><p><Store/>{item.storeName}</p><small>{item.category} • {item.sku} • {date(item.updatedAt)}</small></div><div className={styles.price}><span>FİYAT</span><strong>{money(item.price)}</strong></div>{mode==="stock"?<div className={styles.stockEdit}><span>GÜNCEL STOK</span><div><input type="number" min="0" value={draftStock[item.id]??String(item.stock)} onChange={e=>setDraftStock(v=>({...v,[item.id]:e.target.value}))}/><button disabled={busy===item.id||draftStock[item.id]===undefined} onClick={()=>void saveStock(item)}>{busy===item.id?<RefreshCw className={styles.spin}/>:<Save/>}</button></div><small className={item.stock<=0?styles.danger:item.stock<=5?styles.warn:""}>{item.stock<=0?"Tükendi":item.stock<=5?"Kritik seviye":"Stok sağlıklı"}</small></div>:<div className={styles.stock}><span>STOK</span><strong>{item.stock}</strong><small>{item.source||"seller_panel"}</small></div>}<Link className={styles.open} href="/admin/seller-products"><ArrowUpRight/></Link></article>)}</div>:<Empty text={mode==="mobile"?"Yeni marketplace mobil kanalından henüz taslak gelmedi.":"Yeni satıcı ürün havuzunda bu filtreye uygun kayıt yok."}/>}</section>:null}
  </div>;
}

function Empty({text}:{text:string}){return <div className={styles.empty}><PackageOpen/><h3>Temiz çalışma alanı</h3><p>{text}</p></div>}
function Loading(){return <div className={styles.empty}><RefreshCw className={styles.spin}/><h3>Yeni veriler yükleniyor</h3></div>}
