import { NextRequest, NextResponse } from "next/server";
import { FieldValue } from "firebase-admin/firestore";
import { verifySeller } from "@/lib/apiAuth";
import { adminDb } from "@/lib/firebase.admin";

function text(value:unknown,max:number){return String(value??"").trim().replace(/\s+/g," ").slice(0,max)}
function days(value:unknown,fallback:number){const n=Number(value);return Number.isFinite(n)?Math.min(30,Math.max(1,Math.floor(n))):fallback}

export async function GET(req:NextRequest){const seller=await verifySeller(req);if(seller instanceof NextResponse)return seller;const snap=await adminDb().collection("users").doc(seller.uid).get();const data=snap.data()?.sellerOnboarding||{};return NextResponse.json({ok:true,store:{storeName:data.storeName||seller.storeName,description:data.description||"",website:data.website||"",city:data.city||"",phone:data.phone||"",logoUrl:data.logoUrl||"",bannerUrl:data.bannerUrl||"",shippingDays:data.shippingDays||2,returnDays:data.returnDays||14}})}
export async function PATCH(req:NextRequest){const seller=await verifySeller(req);if(seller instanceof NextResponse)return seller;const body=await req.json();const store={storeName:text(body.storeName,80),description:text(body.description,800),website:text(body.website,240),phone:text(body.phone,24),logoUrl:text(body.logoUrl,1200),bannerUrl:text(body.bannerUrl,1200),shippingDays:days(body.shippingDays,2),returnDays:days(body.returnDays,14)};if(store.storeName.length<2||store.description.length<20)return NextResponse.json({ok:false,error:"Mağaza adı ve en az 20 karakter açıklama gerekli."},{status:400});const db=adminDb(),now=FieldValue.serverTimestamp();const batch=db.batch();batch.set(db.collection("users").doc(seller.uid),{"sellerOnboarding.storeName":store.storeName,"sellerOnboarding.description":store.description,"sellerOnboarding.website":store.website,"sellerOnboarding.phone":store.phone,"sellerOnboarding.logoUrl":store.logoUrl,"sellerOnboarding.bannerUrl":store.bannerUrl,"sellerOnboarding.shippingDays":store.shippingDays,"sellerOnboarding.returnDays":store.returnDays,updatedAt:now},{merge:true});batch.set(db.collection("seller_applications").doc(seller.uid),{...store,updatedAt:now},{merge:true});await batch.commit();return NextResponse.json({ok:true,store});}
