"use client";
import { useEffect,useState,type ChangeEvent,type FormEvent } from "react";
import { Check,ImagePlus,Loader2,Save,Store } from "lucide-react";
import { sellerRequest,sellerUpload } from "@/lib/sellerClient";
import styles from "./store.module.css";
type StoreForm={storeName:string;description:string;website:string;city:string;phone:string;logoUrl:string;bannerUrl:string;shippingDays:number;returnDays:number};
const empty:StoreForm={storeName:"",description:"",website:"",city:"",phone:"",logoUrl:"",bannerUrl:"",shippingDays:2,returnDays:14};
export default function StoreSettingsClient(){const[form,setForm]=useState(empty);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[uploading,setUploading]=useState<"logo"|"banner"|"">("");const[message,setMessage]=useState("");const[error,setError]=useState("");useEffect(()=>{sellerRequest<{store:StoreForm}>("/api/seller/store").then(x=>setForm({...empty,...x.store})).catch(e=>setError((e as Error).message)).finally(()=>setLoading(false));},[]);function set<K extends keyof StoreForm>(key:K,value:StoreForm[K]){setForm(v=>({...v,[key]:value}));}async function upload(event:ChangeEvent<HTMLInputElement>,kind:"logo"|"banner"){const file=event.target.files?.[0];if(!file)return;setUploading(kind);setError("");try{set(kind==="logo"?"logoUrl":"bannerUrl",await sellerUpload(file));}catch(e){setError((e as Error).message);}finally{setUploading("");event.target.value="";}}async function save(event:FormEvent){event.preventDefault();setBusy(true);setError("");setMessage("");try{const data=await sellerRequest<{store:StoreForm}>("/api/seller/store",{method:"PATCH",body:JSON.stringify(form)});setForm({...empty,...data.store});setMessage("Mağaza ayarları güncellendi.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
return <div className={styles.page}><header><div><span>MAĞAZA YÖNETİMİ • 06</span><h1>Vitrinin sana ait.</h1><p>Müşterilerin göreceği mağaza kimliğini ve operasyon sözünü buradan yönet.</p></div><div className={styles.score}><small>VİTRİN SKORU</small><strong>{form.logoUrl&&form.bannerUrl&&form.description?"%100":"%76"}</strong><span><Check/> Güvenli profil</span></div></header>{error?<div className={styles.error}>{error}</div>:null}{message?<div className={styles.success}>{message}</div>:null}{loading?<div className={styles.loading}><Loader2/>Mağaza bilgileri yükleniyor</div>:<form onSubmit={save}><section className={styles.visuals}><label className={styles.banner} style={form.bannerUrl?{backgroundImage:`linear-gradient(rgba(6,10,6,.28),rgba(6,10,6,.65)),url(${form.bannerUrl})`}:undefined}><ImagePlus/><b>{uploading==="banner"?"Yükleniyor…":"Kapak görseli yükle"}</b><small>1600 × 600 önerilir</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e,"banner")}/></label><label className={styles.logo}>{form.logoUrl?<img src={form.logoUrl} alt="Mağaza logosu"/>:<Store/>}<span>{uploading==="logo"?"Yükleniyor…":"Logo değiştir"}</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e,"logo")}/></label><div><small>CANLI ÖNİZLEME</small><h2>{form.storeName||"Mağaza adı"}</h2><p>{form.description||"Mağaza açıklaman burada görünecek."}</p></div></section><section className={styles.form}><div className={styles.formHead}><span>İŞLETME KİMLİĞİ</span><h2>Mağaza bilgileri</h2></div><div className={styles.grid}><label><span>Mağaza adı *</span><input value={form.storeName} onChange={e=>set("storeName",e.target.value)}/></label><label><span>Telefon</span><input value={form.phone} onChange={e=>set("phone",e.target.value)}/></label><label><span>Web sitesi</span><input value={form.website} onChange={e=>set("website",e.target.value)} placeholder="https://"/></label><label><span>Şehir</span><input value={form.city} readOnly/></label><label className={styles.full}><span>Mağaza açıklaması *</span><textarea value={form.description} onChange={e=>set("description",e.target.value)}/><small>{form.description.length}/800</small></label><label><span>Hazırlama süresi</span><select value={form.shippingDays} onChange={e=>set("shippingDays",Number(e.target.value))}>{[1,2,3,4,5,7].map(x=><option key={x} value={x}>{x} iş günü</option>)}</select></label><label><span>İade süresi</span><select value={form.returnDays} onChange={e=>set("returnDays",Number(e.target.value))}>{[7,14,15,30].map(x=><option key={x} value={x}>{x} gün</option>)}</select></label></div><button disabled={busy||!!uploading}>{busy?<Loader2/>:<Save/>} Değişiklikleri kaydet</button></section></form>}</div>}
