"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, Clock3, RefreshCw, Search, ShieldCheck, Store, X } from "lucide-react";
import { getFirebaseAuth } from "@/lib/firebase.client";
import { sellerProductStatusLabel, type SellerProduct, type SellerProductStatus } from "@/lib/sellerTypes";
import styles from "./sellerProducts.module.css";

export default function SuperAdminSellerProductsPage(){
  const [items,setItems]=useState<SellerProduct[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [q,setQ]=useState("");const [filter,setFilter]=useState<"all"|SellerProductStatus>("pending_review");const [busy,setBusy]=useState("");const [notes,setNotes]=useState<Record<string,string>>({});
  const request=useCallback(async(method="GET",body?:unknown)=>{const user=getFirebaseAuth().currentUser;if(!user)throw new Error("Süper Admin oturumu gerekli.");const token=await user.getIdToken();const response=await fetch("/api/admin/seller-products",{method,headers:{Authorization:`Bearer ${token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data?.error||"İşlem başarısız.");return data;},[]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await request();setItems(data.items||[]);}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[request]);useEffect(()=>{void load();},[load]);
  const visible=useMemo(()=>items.filter(item=>(filter==="all"||item.status===filter)&&(!q||`${item.title} ${item.storeName} ${item.sku}`.toLocaleLowerCase("tr").includes(q.toLocaleLowerCase("tr")))),[items,filter,q]);
  async function decide(id:string,status:"approved"|"rejected"|"pending_review"){const note=notes[id]??items.find(x=>x.id===id)?.moderationNote??"";if(status==="rejected"&&note.trim().length<5){setError("Düzeltme isteği için satıcıya en az 5 karakterlik bir not yaz.");return;}setBusy(id);setError("");try{await request("PATCH",{id,status,moderationNote:note});setItems(list=>list.map(x=>x.id===id?{...x,status,moderationNote:note}:x));}catch(e){setError((e as Error).message);}finally{setBusy("");}}
  const pending=items.filter(x=>x.status==="pending_review").length;const approved=items.filter(x=>x.status==="approved").length;
  return <div className={styles.page}><header className={styles.hero}><div><span>SÜPER ADMİN • MARKETPLACE QUALITY</span><h1>Ürün Onay Merkezi</h1><p>İşletmelerden gelen ürünleri kalite, fiyat ve katalog standartlarına göre değerlendir.</p></div><div className={styles.metrics}><span><small>BEKLEYEN</small><b>{pending}</b></span><span><small>YAYINDA</small><b>{approved}</b></span></div></header>{error?<div className={styles.error}>{error}</div>:null}<section className={styles.toolbar}><label><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ürün, mağaza veya SKU ara"/></label><div>{(["pending_review","all","approved","rejected"] as const).map(key=><button key={key} className={filter===key?styles.active:""} onClick={()=>setFilter(key)}>{key==="all"?"Tümü":sellerProductStatusLabel[key]}</button>)}</div><button onClick={load}><RefreshCw size={16}/></button></section><section className={styles.list}>{loading?<div className={styles.empty}><RefreshCw className={styles.spin}/>Ürünler yükleniyor</div>:visible.length===0?<div className={styles.empty}><ShieldCheck/>Bu kuyruk temiz.</div>:visible.map(item=><article key={item.id}><div className={styles.image}>{item.images?.[0]?<img src={item.images[0]} alt=""/>:<Store/>}</div><div className={styles.identity}><span className={styles[item.status]}>{sellerProductStatusLabel[item.status]}</span><h2>{item.title}</h2><p><Store size={13}/>{item.storeName}</p><small>{item.category} · SKU {item.sku}</small></div><div className={styles.commercial}><span><small>FİYAT</small><b>{item.price.toLocaleString("tr-TR",{style:"currency",currency:"TRY"})}</b></span><span><small>STOK</small><b>{item.stock}</b></span></div><div className={styles.description}>{item.description}</div><label className={styles.note}><span>İŞLETMEYE NOT</span><input value={notes[item.id]??item.moderationNote??""} onChange={e=>setNotes(v=>({...v,[item.id]:e.target.value}))} placeholder="Onay veya düzeltme notu…"/></label><div className={styles.actions}><button disabled={busy===item.id} onClick={()=>decide(item.id,"approved")}><Check/>Onayla</button><button disabled={busy===item.id} onClick={()=>decide(item.id,"rejected")}><X/>Düzeltme iste</button><button disabled={busy===item.id} onClick={()=>decide(item.id,"pending_review")}><Clock3/></button></div></article>)}</section></div>;
}
